### ISSUE TITLE
Fix major bug in the Exception

### ISSUE THREAD

**Issue by xapdkop** [xapdkop/BloomFramework#17]
**Describe the bug**
Exception may thrown an exception in the constructor if there are no free memory

**To Reproduce**
1. SDL fails to allocate memory (e.g. for texture/surface), sets "Out of memory error" and  returns `nullptr`.
2. The texture is checked on nullptr and ('cause it's null) exception is thrown
3. When constructing `bloom::Exception` (and before it) there may be memory allocation for std::string.
4. Because there are no free memory, std::string throws an exception.

**Expected behavior**
Remove all memory allocations (i.e. replace std::string with c-string)!

**Comment by LumpBloom7** [comment]
This would seem like a very rare occurrence...

However that may not always be the case, Textures are stored on VRAM(usually dedicated or reserved ahead of time) etc.

But nevertheless it's still a valid(though rare) problem 

Would `string_view` help?

**Comment by xapdkop** [comment]
But why and how string_view is better then char*? Since string referenced by string_view **may be destroyed** because of stack unwinding (if this string is `std::string`). Also, there are a lot of (or even all) error messages (or buffers for them) are known in advance, so they are already created at program startup.

**Comment by xapdkop** [comment]
Since `SDL_GetError` returns const char* (and holds buffer for error message), it's possible to just add another char* field to `Exception` to hold from where exception was thrown. So `Exception::what` will return sdl's message and `Exception::where` will return the name of the function, where exception caught.

**Comment by LumpBloom7** [comment]
@xapdkop A string view is capable of holding the pointers stuff of c-style strings if I'm not wrong, so it would not need to allocate memory.

**Comment by xapdkop** [comment]
No, I meant that something like this https://github.com/xapdkop/BloomFramework/blob/d40d425960019a95cf6a08af1151a5f7fa95ffed/BloomFramework/src/Game.cpp#L75 is not good and may be (and already) optimized. But ok, string_view may be helpful for messages such as "file %filename% not found" since if I understood correctly, the message will be copied in the `std::exception`'s constructor.

**Comment by xapdkop** [comment]
Done https://github.com/BloomCreativeWorks/BloomFramework/pull/33.
