### ISSUE TITLE
Access violation when closing Test Bench, w/ Audio

### ISSUE THREAD

**Issue by xapdkop** [xapdkop/BloomFramework#3]
Sometimes thrown "0xC0000005: Access violation executing location" exception from libmpg123-0.dll when closing Test Bench.

**Comment by xapdkop** [comment]
It seems that it occurs 'cause of dtor for Game called after Game::exit(). Mb put dtors of uses class into Game::destroy.

**Comment by xapdkop** [comment]
Needs rework of Game::exit()

**Comment by LumpBloom7** [comment]
Resolved in https://github.com/xapdkop/BloomFramework/commit/ed184710b390b69b2270bf2ccf075283a72b178c
