### ISSUE TITLE
Replace std::string with std::filesystem for file paths

### ISSUE THREAD

**Issue by xapdkop** [xapdkop/BloomFramework#7]
- [x] Texture
- [x] Audio (beta)
- [x] fix problem with different paths (current and executable)

**Comment by LumpBloom7** [comment]
That was actually one of my plans.

**Comment by xapdkop** [comment]
@LumpBloom7, but now it's my plan ;)

**Comment by LumpBloom7** [comment]
@xapdkop, no. OUR plan!

**Comment by xapdkop** [comment]
@LumpBloom7 hahaha, u're naive. If I say "my plan", it means that it's my plan!

**Comment by LumpBloom7** [comment]
Fine

**Comment by xapdkop** [comment]
Yup!
